### ISSUE TITLE
如何处理异步请求中奖信息时轮盘的转动问题

### ISSUE THREAD

**Issue by cgletufo** [coffeedeveloper/turntable#4]
问题： 只能在请求返回后才能开始转动到指定位置。
需求： 请求中奖信息的过程中可以转动，在请求返回时转动到指定位置

**Comment by coffeedeveloper** [comment]
truntable本身就支持start和stop的方法的。你仔细看下文档。你可以在接口请求前开始start，然后等接口返回后拿到奖品id在stop。
